# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Joe Redmond Portfolio
# Description of the Site
description: I have been programming for over 5 years, specializing in the jvm and treating software engineering as a career not a paycheck.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Java, jvm, software engineer, software engineering, programming, coding, coder, backend developer, developer, fullstack developer, sql developer
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: me@josephredmond.com
facebook_username:
twitter_username:
instagram_username:
linkedin_username: joseph-redmond
github_username:  joseph-redmond
youtube_channel_id: UCRoN-yt1tal2n3nYnQiD85g
reddit_username: joey_the_god_of_code
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-211802032-1

# Disqus
disqus-shortname: joey-the-god-of-code

# Name of the Author
author-name: Joe Redmond
# URL for the Image of the Author
author-image: /WhatATheme/assets/images/bio-photo.jpg
# 60 Words About the Author
author-about: Hi, I'm Joseph Redmond (Joe for short). I am a software engineer specializing in the jvm with over 5 years of programming experience.
  I'm teaching mentees about the world of software engineering and want to help the next generation
  of developers advance forward. I am available for contract work just send me a message and let's get started.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/joseph-redmond

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
